# Generated by Django 5.2.8 on 2025-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_facture', '0002_alter_invoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(max_length=255),
        ),
    ]
